
image:
    file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/43_config_ports/
ports:
    - port: 3000
github:
    prebuilds:
        # enable for the master/default branch (defaults to true)
        master: true
# enable for all branches in this repo (defaults to false)
        branches: true
# enable for pull requests coming from this repo (defaults to true)
        pullRequests: true
# enable for pull requests coming from forks (defaults to false)
        pullRequestsFromForks: true
# add a check to pull requests (defaults to true)
        addCheck: true
# add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
        addComment: true
# add a "Review in Gitpod" button to the pull request's description (defaults to false)
        addBadge: true
# add a label once the prebuild is ready to pull requests (defaults to false)
        addLabel: true
# List the start up tasks. You can start them in parallel in multiple terminals. See https://www.gitpod.io/docs/44_config_start_tasks/
tasks:
    - init: >
        flutter channel master
        flutter upgrade
        flutter config --enable-web
        rustup update
        rustup component add clippy
        cargo install wasm-pack 
        cargo install cargo-generate
        
        npm install npm@latest -g
        cargo install --path . &&
        cargo test

vscode:
  extensions:
    - vadimcn.vscode-lldb
    - pinage404.rust-extension-pack
    - hbenl.vscode-test-explorer
