name: flutter_web_wasm
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Sach97 <sacha.arbonel@hotmail.fr>

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #js: ^0.6.3
  js:
    git:
      url: https://github.com/dart-lang/sdk.git
      path: pkg/js

dev_dependencies:
  pedantic: ^1.8.0
  # test: ^1.3.0